In [2]:
import os
os.system('pip freeze')


0

In [1]:
import cv2

In [76]:
import numpy as np
transform = np.array([[2,0,0], [0,1,0], [0,0,1]], dtype="float32")# ito
#transform = np.array([np.array([[1,0,0], [0,1,0], [0,0,1]], dtype="float32")])# ito
a = np.array([[1,1]], dtype="float32")# ito
#a = np.array([[[10,1],[10,1],[10,1]]], dtype="float32")# ito
#a = np.array([10,12,1], dtype="float32")# ito
#a = np.array([[10,12,1],[10,1,1],[10,12,1]], dtype="float32")# ito
#a = np.array([np.array([[10,12]], dtype="float32")])# ito
output = cv2.perspectiveTransform(a[None,:,:], transform)

In [74]:
#a = np.array([np.array([[102, 23]], dtype="float32")])# ito
a = np.array([[[102, 23]]], dtype="float32")# ito

In [72]:
print a

[[ 1.  1.]]


In [73]:
output

array([[[ 2.,  1.]]], dtype=float32)

In [70]:
output.size

2

In [77]:
g=range(10)

In [79]:
[ar for ar in g]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
a=[[[[[  1.17065680e+00   2.67476380e-01]]], [[[  1.17030055e+00   7.76088875e-01]]],[[[  1.17030055e+00   7.76088875e-01]]]]]

SyntaxError: invalid syntax (<ipython-input-80-92f92b325ed0>, line 1)

In [91]:
a=[[[[  1.17065680e+00,   2.67476380e-01]]], [[[  1.17030055e+00,   7.76088875e-01]]],[[[  1.17030055e+00,   7.76088875e-01]]]]

In [90]:
a=[1, 2]
print a[0]

1


In [94]:
a=[[[[  1.17065680e+00,   2.67476380e-01]]], [[[  1.17030055e+00,   7.76088875e-01]]],[[[  None,  None]]]]

In [95]:
print a

[[[[1.1706568, 0.26747638]]], [[[1.17030055, 0.776088875]]], [[[None, None]]]]


In [96]:
a2=a.reshape([1,6])

AttributeError: 'list' object has no attribute 'reshape'

In [150]:
b = np.array([[[[[1, 3]]], [[[2, 1]]], [[[None, None]]]],[[[[1, 3]]], [[[4, 5]]], [[[None, None]]]]])

In [149]:
b = np.array([[[[[1, 3]]], [[[2, 1]]], [[[nan, nan]]]],[[[[1, 3]]], [[[4, 5]]], [[[None, None]]]]])

NameError: name 'nan' is not defined

In [151]:
print b

[[[[[1 3]]]


  [[[2 1]]]


  [[[None None]]]]



 [[[[1 3]]]


  [[[4 5]]]


  [[[None None]]]]]


In [153]:
for ar in b:
    print ar

[[[[1 3]]]


 [[[2 1]]]


 [[[None None]]]]
[[[[1 3]]]


 [[[4 5]]]


 [[[None None]]]]


In [160]:
ar[:,:,:,0]

array([[[1]],

       [[4]],

       [[None]]], dtype=object)

In [147]:
#c=b.reshape((3, 4,1))
#b[:, :, :, :, 0]
d=b[:,:,:,:,1]
d

array([[[[3]],

        [[1]],

        [[None]]],


       [[[3]],

        [[5]],

        [[None]]]], dtype=object)

In [148]:
e=d.reshape((3, 2))
e

array([[3, 1],
       [None, 3],
       [5, None]], dtype=object)

In [141]:
e

array([[1, 2],
       [None, 1],
       [4, None]], dtype=object)

In [164]:
f=e.copy()
f

array([[3, 1],
       [None, 3],
       [5, None]], dtype=object)

In [166]:
pt=[]

In [171]:
import matplotlib.pyplot as plt
plt.plot([0, 1], [1, 2])
plt.imshow

<function matplotlib.pyplot.imshow>

In [172]:
grid_x, grid_y = np.mgrid[0:1:100j, 0:1:200j]

In [173]:
grid_x

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01010101,  0.01010101,  0.01010101, ...,  0.01010101,
         0.01010101,  0.01010101],
       [ 0.02020202,  0.02020202,  0.02020202, ...,  0.02020202,
         0.02020202,  0.02020202],
       ..., 
       [ 0.97979798,  0.97979798,  0.97979798, ...,  0.97979798,
         0.97979798,  0.97979798],
       [ 0.98989899,  0.98989899,  0.98989899, ...,  0.98989899,
         0.98989899,  0.98989899],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

In [175]:
ab=[[[ 1.1706568,   0.26747638]]]

In [204]:
#print ab
abc=ab[0]
abcd=abc[0]
abcd[1]

0.26747638

In [212]:
a=np.array([[[ 1.1706568,   0.26747638], [ 1.16995749,  1.26586387],[ 1.16925818,  2.26425136]]])

In [219]:
b=a[0]

In [226]:
df=np.array([0,1,'nan'])

In [227]:
import pandas as pd
df.replace(np.nan,'0')


AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [ ]:
if math.isnan(mx[i]):